### ISSUE TITLE
Decimal values?

### ISSUE THREAD

**Issue by sorxrob** [bumbeishvili/covid19-daily-data#1]
Hi, thanks for this. I'm trying to play with it and noticed some data containing decimals.

![Screen Shot 2020-03-26 at 4 45 39 PM](https://user-images.githubusercontent.com/13049130/77627094-54a84680-6f81-11ea-9879-a36da614d007.png)

Thanks again.

**Comment by bumbeishvili** [comment]
Please read the description, it contains several changes I applied  
![Screen Shot 2020-03-26 at 12 52 02](https://user-images.githubusercontent.com/6873202/77627623-9e346980-6f60-11ea-805b-b3f129ee42a5.png)

**Comment by bumbeishvili** [comment]
23 March data is also manually modified because It was same, I averaged it based on next and day before data, it may be 10-15 % incorrect for this particular day, but earlier data was 100% incorrect

**Comment by sorxrob** [comment]
Alright. Thank you!
