### ISSUE TITLE
Deaths file mistakenly updated with Recovered data

### ISSUE THREAD

**Issue by jsidew** [bumbeishvili/covid19-daily-data#12]
https://github.com/bumbeishvili/covid19-daily-data/commit/dae25a3ce66ecbb336a5e4b3faf847cc686ffd8a#diff-aebe72655ea58899b1f3dd64410a4b99

**Comment by bumbeishvili** [comment]
Thank you very much for the report, I will fix it shortly

**Comment by bumbeishvili** [comment]
Fixed
