### ISSUE TITLE
Spain no recovered?

### ISSUE THREAD

**Issue by KnowsCount** [bumbeishvili/covid19-daily-data#14]
I dont believe there are no recover cases in Spain..

![](https://knowscount-1304485449.cos.ap-shanghai.myqcloud.com/img/Screenshot%202020-12-12%20at%2021.54.30.png))

The project used your API..

**Comment by bumbeishvili** [comment]
Data is based on Worldometers, where spain `N/A` as recovered
<img width="1386" alt="Screenshot 2020-12-14 at 10 28 49" src="https://user-images.githubusercontent.com/6873202/102047717-2f9d8180-3df7-11eb-9586-da36519fed44.png">

**Comment by KnowsCount** [comment]
this may cause some confusion.. anyway thanks!
