### ISSUE TITLE
Just thank you for the repo! Imho it's the most consistent data representation.

### ISSUE THREAD

**Issue by PhantomYdn** [bumbeishvili/covid19-daily-data#3]
Finally fixed my notebook with data: https://observablehq.com/@phantomydn/covid-2019-stats-country-state-selection

But why data from china for last 3 days are not integers?

**Comment by bumbeishvili** [comment]
Thank you

Regarding your question:
![Screen Shot 2020-03-27 at 09 45 50](https://user-images.githubusercontent.com/6873202/77725776-c8913000-700f-11ea-9b78-bef230781b0d.png)

Please read the description in the readme, it will explain some of the changes I made
