### ISSUE TITLE
1 day delay?

### ISSUE THREAD

**Issue by sorxrob** [bumbeishvili/covid19-daily-data#9]
Hi!

Is it normal that the last date is April 19? Are there some delays?

Also looks like [CSSEGISandData](https://github.com/CSSEGISandData/COVID-19) continued supplying [recovered data](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv).

Thanks.

**Comment by bumbeishvili** [comment]
Hello, I am usually updating it between 10 a.m - 11:59 a.m GMT+4

Regarding recovered data:
![Screen Shot 2020-04-21 at 10 04 21](https://user-images.githubusercontent.com/6873202/79830976-9c22c680-83b7-11ea-8947-8ab248ab3809.png)

**Comment by bumbeishvili** [comment]
Just saying, I had to adapt to their structural changes basically in every 3-4 days, which took much more time, than building my own data repo

**Comment by sorxrob** [comment]
> Just saying, I had to adapt to their structural changes basically in every 3-4 days, which took much more time, than building my own data repo

Yes, can't rely on their data. Too much changes. Thanks!

**Comment by sorxrob** [comment]
hey @bumbeishvili  just so you know, I am using your data in my 3d vis app https://covid3d.live

I referenced you on the repo

**Comment by bumbeishvili** [comment]
Great, I will add it in the list

**Comment by bumbeishvili** [comment]
It's a very impressive visualization (Y), I see that you added a recording of history as well,  It's a good feature
